feature: ['feature/*', 'feat/*']
bug: ['fix/*', 'bugfix/*']
maintenance: ['maintenance/*', 'cleanup/*']
dependencies: ['dependencies/*', 'deps/*']
breaking: ['breaking/*', 'major/*']
enhancement: ['enhancement/*', 'improvement/*']
documentation: ['docs/*', 'documentation/*']
