# Config file for automatic testing at travis-ci.org
language: python
python:
  - "3.6"
  - "3.7.6"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements/test.txt
  - pip install .
# command to run tests
script: pytest
