language: python
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- 3.7.5
- 3.7.6
- '3.8'
install:
- pip install -r requirements/test.txt
- pip install -r requirements/dev.txt
- pip install .
script:
- flake8
- mypy src/collectionish
- pytest
- make dist && twine check dist/*
deploy:
  provider: pypi
  user: __token__
  password:
    secure: N8TA3ZIf1iI21WuhkuUqmC6tZbvR4WFe1Fmun8x7Jk0Cu0l54kSPFnBSaP+NtHJueFLhUVzl3voYDAQMnEleZWXRd/RKLr63KEDaIHUksW/fWzJiYxcSxpcMKPVtq+t5G4kgiKmanp6pSC7DwIk8mkhkIEMhKCeA+N85Ob0TGHvLug5uxSbM1n5A5YsNyt0KkOteb5qtcJdaqnfcL5suYEWSB3eWGB65jWbnULlDl0I0NG6HtNimeGHG8uJvasvhmxWO6nqTaaAo7iQw1B722OJaZo70k4oce9ZThw5pt5KXx1PMFpaROa4ckRFt/AM8NWunjw3KuVbpbc4zIxJbzEdIWMuFsEyV3jV1vSuzl80nymr/ojjxdNCxCHzb9b8LHH1T7axpwHc+PKxuU0Lcvupr9HcQARuhBrUZPd2R3xhkxrWHVwnadP5If+dZCut9+FsJs5/GVoYkaAduKmSEQJ/KviXJmp+f0e2C/4ktSweW6mqPULcJN/jl3OgSFcbSpCdB/3hh6cCZ6xay/aPIL+yyGXeH14qr+ZFKFvUWqJeYxSSgMochiuCQeXijSaKdCxouQZT5/rNZtPht5kq2xBCbnGvjO8RFWA/Vn6lm3+G2WnkfUdc1lxCBNdTJtVOc8fsqICNPaIfddsvN2LMTcT+4+XD+FeLd6GeA+a7rmFM=
  skip_existing: true
  on:
    tags: true
