language: python
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- 3.7.7
- '3.8'
install:
- pip install -r requirements/test.txt
- pip install -r requirements/dev.txt
- pip install codecov
- pip install .
script:
- flake8
- mypy src/collectionish
- pytest --cov collectionish --benchmark-compare
after_success:
- codecov
