#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# more_containers documentation build configuration file, created by
# sphinx-quickstart on Fri Jun  9 13:47:02 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another
# directory, add these directories to sys.path here. If the directory is
# relative to the documentation root, use os.path.abspath to make it
# absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath('../src'))

import more_containers

import sphinx_material


# -- Extensions to the  Napoleon GoogleDocstring class ---------------------

"""
this snippit is in part from michael gorez's post 
https://michaelgoerz.net/notes/extending-sphinx-napoleon-docstring-sections.html
here we just want to assure the more compact ivar style class attibutes are still called `Attributes` 
( instead of variables which is napoleans default )
"""

from sphinx.ext.napoleon.docstring import GoogleDocstring


def parse_attributes_section(self, section):
    return self._format_fields('Attributes', self._consume_fields())


GoogleDocstring._parse_attributes_section = parse_attributes_section


# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    # napolean for google style docstrings
    'sphinx.ext.napoleon',
    'sphinx.ext.autosectionlabel',
]

autodoc_member_order = 'bysource'

napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_use_param = False
napoleon_use_rtype = False
napoleon_use_ivar = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'More Containers'
copyright = u"2019, Lea Provenzano"
author = u"Lea Provenzano"

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = more_containers.__version__
# The full version, including alpha/beta/rc tags.
release = more_containers.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

highlight_language = 'python3'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#

# Theme options are theme-specific and customize the look and feel of a
# theme further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'more_containersdoc'


# -- Options for LaTeX output ------------------------------------------

# latex_elements = {
#     # The paper size ('letterpaper' or 'a4paper').
#     #
#     # 'papersize': 'letterpaper',

#     # The font size ('10pt', '11pt' or '12pt').
#     #
#     # 'pointsize': '10pt',

#     # Additional stuff for the LaTeX preamble.
#     #
#     # 'preamble': '',

#     # Latex figure (float) alignment
#     #
#     # 'figure_align': 'htbp',
# }

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass
# [howto, manual, or own class]).
# latex_documents = [
#     (master_doc, 'more_containers.tex',
#      u'More Containers Documentation',
#      u'Lea Provenzano', 'manual'),
# ]


# -- Options for manual page output ------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
# man_pages = [
#     (master_doc, 'more_containers',
#      u'More Containers Documentation',
#      [author], 1)
# ]


# -- Options for Texinfo output ----------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
# texinfo_documents = [
#     (master_doc, 'more_containers',
#      u'More Containers Documentation',
#      author,
#      'more_containers',
#      'One line description of project.',
#      'Miscellaneous'),
# ]

import sphinx_material

# Required theme setup
extensions.append('sphinx_material')
html_theme = 'sphinx_material'
html_theme_path = sphinx_material.html_theme_path()
html_context = sphinx_material.get_html_context()
html_show_sourcelink = False

# # Material theme options (see theme.conf for more information)
html_theme_options = {
    # Set the name of the project to appear in the navigation.
    'nav_title': 'more-containers',
    #     # Set you GA account ID to enable tracking
    #     'google_analytics_account': 'UA-XXXXX',
    #     # Specify a base_url used to generate sitemap.xml. If not
    #     # specified, then no sitemap will be built.
    # 'base_url': 'https://project.github.io/project',
    #     # Set the color and the accent color
    #     'color_primary': 'blue',
    #     'color_accent': 'light-blue',
    #     # Set the repo location to get a badge with stats
    'repo_url': 'https://github.com/leaprovenzano/more-containers/',
    'repo_name': 'more-containers',
    'html_minify': True,
    'css_minify': True,
    #     # Visible levels of the global TOC; -1 means unlimited
    # 'globaltoc_depth': 2,
    #     # If False, expand all TOC entries
    'globaltoc_collapse': False,
    #     # If True, show hidden TOC entries
    'globaltoc_includehidden': False,
}

html_sidebars = {"**": ["logo-text.html", "globaltoc.html", "localtoc.html", "searchbox.html"]}
